name: sixcore
description: Sixcore Workout Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  infinite_listview: ^1.1.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_core: ^20.3.57
  syncfusion_flutter_charts: ^20.3.57
  permission_handler: ^10.2.0
  flutter_blue: ^0.8.0
  device_info_plus: ^8.0.0
  platform_device_id: ^1.0.1
  connectivity_plus: ^3.0.2
  wakelock: ^0.6.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  firebase_ui_firestore: ^1.1.0
  app_settings: ^4.1.8
  horizontal_picker: ^1.2.0
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.2
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
